//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiagramaDeporteFavorito1.Diagramas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_ingreso
    {
        public int idDetalleIngreso { get; set; }
        public Nullable<int> idIngreso { get; set; }
        public Nullable<int> idArticulo { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> total { get; set; }
    
        public virtual Articulos Articulos { get; set; }
        public virtual Ingreso Ingreso { get; set; }
    }
}
